### ISSUE TITLE
How can NDCG be calculated for WikiQA?

### ISSUE THREAD

**Issue by aneesh-joshi** [faneshion/MatchZoo#109]
Hi,
I'm going through the MatchZoo code for getting ndcg@k values for various models on WikiQA.
I can't really understand how wikiqa can be used in NDCG at all!

For example,
for a given query, q1, there are several candidate documents d1, d2, d3.
the `y_true` values are `[1, 0, 0]`
The model will provide a `y_pred` which will be the respective dot products of the query with each of the documents.
`y_pred = [-0.96715796, 0.9667174, 0.97257483]`

From just this data, how is it even possible to infer the ranks that out system has given?
if we consider y_pred values as relative ranks, then the ranking is d3, d2, d1

`dcg@3` would be `rel3  + rel2/log3 + rel1/log4`
and Ideal `dcg@3` would also be the same, ie, `rel3  + rel2/log3 + rel1/log4`

and thus `ndcg@3` would be `(rel3  + rel2/log3 + rel1/log4)/(rel3  + rel2/log3 + rel1/log4)` = always  `1`

Moreover, we never made of the true relevance, ie, `y_true`
This overall doesn't make any sense to me.

I would be really grateful if someone could help me make sense.
@faneshion @yangliuy @bwanglzu

**Comment by aneesh-joshi** [comment]
Here is an actual instance while evaluating wikiqa code

`ndcg@3`
y_true[pre: suf] is  `[1 0 0]`

y_pred is  
`[-0.96715796, 0.9667174, 0.97257483]`
 
result:
`ndcg@3 = 0.5`

**Comment by aneesh-joshi** [comment]
Another example:

```
ndcg@5 
y_true[pre:suf] is  [1 0 0 0 0 0]  
y_pred is  [ 0.9705702, -0.9754324, 0.9737232, 0.8897103, 0.9523903, 0.9374584]
ndcg@5 is  0.6309297535714574
```

**Comment by bwanglzu** [comment]
I'm not sure my understanding towards your question is correct, but nDCG should evaluate **relatedness**, such as [0.7, 0.9, 0.2, 0.4, 0.5, 0.0, 0.3] (should be a list of positive values indicates the relatedness).

The `y_true` you provided should be clicked/not-clicked, right? According to my understanding, nDCG is not quite useful when evaluating such binary labels.

**Comment by aneesh-joshi** [comment]
as per [this](http://fastml.com/evaluating-recommender-systems/) post by FastML:
> The main difference between the two is that MAP assumes binary relevance (an item is either of interest or not), while NDCG allows relevance scores in form of real numbers. The relation is just like with classification and regression

This supports my point that evaluating NDCG on WikiQA doesn't make any sense.

If this is in fact correct, the benchmarks be corrected by removing NDCG for the WikiQA dataset.

What do you think, @yangliuy ?

**Comment by bwanglzu** [comment]
@aneesh-joshi Basically, you're evaluating clickthrough data was represented as 1-relevant or 0-not_relevant.

![precision](<a href="https://www.codecogs.com/eqnedit.php?latex=precision&space;=&space;\frac{RelevantDocs\bigcap&space;RetrievedDocs}{RetrievedDocs}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?precision&space;=&space;\frac{RelevantDocs\bigcap&space;RetrievedDocs}{RetrievedDocs}" title="precision = \frac{RelevantDocs\bigcap RetrievedDocs}{RetrievedDocs}" /></a>)

based on the assumption of *clicked=relevant*. So, Precision, Recall, AP, mAP, F1, MRR(Mean reciprocal rank), and all@k is useful for this situation.

For the situation of Non-binary relevance measurement, we use nDCG to evaluate the `usefulness` (say cumulative gain) of each document. So it's not meaningful to use nDCG to evaluate binary labels (because information gain always equals to 1 or 0). 

I'd say let's keep the evaluation framework to be unified at the moment since the user of MatchZoo should clearly understand which evaluation metric makes sense for his/her specific situation.

Instead of a random blog post, I would suggest you read [evaluation metrics: irbook](https://nlp.stanford.edu/IR-book/html/htmledition/evaluation-of-ranked-retrieval-results-1.html) written by Christopher Manning since it's more formal & easy to understand.

**Comment by aneesh-joshi** [comment]
For reference of others, @bwanglzu is replying to a comment I later deleted, citing [this](http://fastml.com/evaluating-recommender-systems/) site:
>MAP is a metric for binary feedback only, while NDCG can be used in any case where you can assign relevance score to a recommended item (binary, integer or real).


For clarification, @bwanglzu , are you agreeing that nDCG cannot be used for binary classification like that of WikiQA dataset?

Also, MAP, precision, etc. are better measures for nDCG?

**Comment by bwanglzu** [comment]
@aneesh-joshi I'd say it can be evaluated with nDCG, but not meaningful for binary retrieval problem. 

For binary retrieval problem (say the labels are 0 or 1 indicates relevant or not), we use P, AP, MAP etc.

For non-binary retrieval problem (say the labels are real numbers greater equal than 0 indicates the "relatedness"]), we use nDCG.

In this situation, clearly, mAP@k is a better metric than nDCG@k.

**Comment by aneesh-joshi** [comment]
Thank you very much for that clarification! I've been rattling my brain for days trying to figure out how nDCG is used here.

What about QuoraQP dataset. Since it's either relevant or not, i.e., there are only 2 ranks, would nDCG be applicable there or is MAP, P@k, etc still better?

Also, I don't  understand your reasoning for not removing it
>since the user of MatchZoo should clearly understand which evaluation metric makes sense for his/her specific situation.

Isn't it lead to more people who get confused like me?

**Comment by bwanglzu** [comment]
The previous metrics are all Information Retrieval Metrics. The output should be sorted (for non-binary retrieval situation) list, each value represents how likely this document is related to this query.
Input: Query & List of document to be ranked -> Output: Sorted list of Relevance Scores -> Evaluate: nDCG.

For Quora Question Pair duplicate detection problem, out output is a probability between [0,1] indicates the degree of duplicates, **More importantly, the output has no internal relationship (independent)**
Input: List of question pairs  2 -> Output: list of probability -> Evaluation: Machine Learning Evaluation Metrics such as cross-entropy loss.
