### ISSUE TITLE
Production Ready 

### ISSUE THREAD

**Issue by augmen** [faneshion/MatchZoo#129]
can we utilise the match zoo for production ready applications? can we make a full text search engine for Question and answer database application using match zoo ? if yes how to add the Question and answer database to the match zoo ? Database like a json file "Question", {q1}: "Answer",{a1}

**Comment by bwanglzu** [comment]
Hi, @augmen I guess you wish to train a model with MatchZoo and integrate the model  (not MatchZoo) into your production environment?

**Comment by uduse** [comment]
It's ok to use MatchZoo commercially since it's licensed under Apache-2.0, [more details here](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)).

And in response to  "adding QA database," it's not MatchZoo designed for. I recommend extracting nuts and guts of MatchZoo (preprocessing utils and model structures) and make your own version.

**Comment by yangliuy** [comment]
Do you have answer correctness annotations in your data ? If yes, you can use MatchZoo to train a model for your data. Otherwise, you need to consider transfer learning from other existing QA data sets.
