### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by ArthurCamara** [faneshion/MatchZoo#17]
Hi there!

Any info on when (and if) we will have GPU support for the models?

Thanks!

**Comment by yangliuy** [comment]
MatchZoo is developed using Keras/TensorFlow. Thus the usage of MatchZoo on GPU is the same with that of TensorFlow. You can refer to https://www.tensorflow.org/tutorials/using_gpu . You can type "nvidia-smi" to check whether your process is on GPU or not.

**Comment by loveJasmine** [comment]
I also got this issue, it always run on CPU
however, my other tensorflow based project can use GPU

**Comment by uduse** [comment]
The problem is that in `setup.py`, `tensorflow` is required a its CPU version:

https://github.com/faneshion/MatchZoo/blob/a4a8ee7e8b7d1d0a8f4b8bd09764d509fc59d2d6/setup.py#L33

I guess the team have `tensorflow-gpu` installed forehand so they didn't notice this. To resolve this issue, try:

```
pip uninstall tensorflow
pip install tensorflow-gpu
```

and set your environment variable like in other projects.

**Comment by tramya28** [comment]
Hello,
I did the exact same instructions. Installed tensorflow-gpu and i dont have tensorflow (CPU version). I run the deep learning models and they are still running on the CPU but not on GPU. Is there anything else i have to do to make them run on GPU?

**Comment by uduse** [comment]
Maybe this will help you: https://github.com/tensorflow/tensorflow/issues/12388 Maybe you forgot to set CUDA_VISIBLE_DEVICES? Notice that this is a tensorflow related problem instead of Matchzoo's. Matchzoo does not manage the underlying hardware its backend uses.
