### ISSUE TITLE
a question about DRMM model

### ISSUE THREAD

**Issue by pwlazy** [faneshion/MatchZoo#181]
in the paper, "z(l) =tanh(W(l)z(l−1) +b(l))   i=1,...,M,l=1,...,L"
you can see the activation tanh is used for every full connection layer

but in the code(drmm.py), there is little difference
```
    for i in range(self.config['num_layers']-1):
            z = Dense(self.config['hidden_sizes'][i], kernel_initializer=self.initializer_fc)(z)
            z = Activation('tanh')(z)
            show_layer_info('Dense', z)
   z = Dense(self.config['hidden_sizes'][self.config['num_layers']-1], kernel_initializer=self.initializer_fc)(z)
```
the activation tanh is not used for the last full connection layer

why the difference exist? why not add a the activation tanh for the last full connection layer

**Comment by thiziri** [comment]
@faneshion 
I'm working with TREC datasets, do I need to add the last tanh activation so? Since I still could not get comparable results with those of the published results in the [DRMM paper](http://www.bigdatalab.ac.cn/~gjf/papers/2016/CIKM2016a_guo.pdf) while using the same dataset Robust?
Thanks

**Comment by faneshion** [comment]
@thiziri For TREC datasets, it is better to add `tanh` activation. By the way, there are some tricks in sampling train instances to keep data balance in the [original code](!https://github.com/faneshion/DRMM). Since the query number is limited, it's very easy to be dominated by some query with more positive samples.

**Comment by thiziri** [comment]
Thanks for your response @faneshion ,
Could you clarify more on this point, please? 

> Since the query number is limited, it's very easy to be dominated by some query with more positive samples.
Thanks again
